FROM python:3.10

WORKDIR /app

# 必要なパッケージをインストール
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Poetryのインストール
ENV POETRY_HOME="/opt/poetry" \
    POETRY_VIRTUALENVS_CREATE=false
RUN curl -sSL https://install.python-poetry.org | python3 -
ENV PATH="$POETRY_HOME/bin:$PATH"

# プロジェクトファイルをコピー
COPY . /app/

# 依存関係をインストール
RUN poetry install --no-interaction --no-ansi --with dev

# テストを実行するコマンド
CMD ["poetry", "run", "pytest", "tests/", "-v", "--cov=app", "--cov-report=html", "--cov-report=term-missing"] 