version: '3.8'

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      # テスト結果とカバレッジレポートをホストにマウント
      - ./htmlcov:/app/htmlcov
      - ./test-results:/app/test-results
    environment:
      - PYTHONPATH=/app
      - PYTEST_ADDOPTS="--junitxml=/app/test-results/junit.xml"
    # テスト終了後にコンテナを削除
    command: >
      sh -c "
        pytest tests/ -v --cov=app --cov-report=html --cov-report=term-missing --junitxml=/app/test-results/junit.xml
      " 